### ISSUE TITLE
add multiple page in react

### ISSUE THREAD

**Issue by NdeyeThiane** [NdeyeThiane/tictactoe_game2.0#1]
I wanted to be able to have multiple pages, but it ended up looking like this

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
    <Home />

https://github.com/user-attachments/assets/43d7f62a-2075-4bf0-8630-dbdb5d064cdf

  </StrictMode>,
);

**Comment by MBHunter88** [comment]
Can I be assigned this issue?

**Comment by NdeyeThiane** [comment]
Sure, let me assign it to you
